export const demoData = [
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 300,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 400,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 500,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
  {
    requestUrl: '/sdfsdfsdf/jkljke/kjjio',
    requestBody: '',
    requestMethod: 'POST',
    requestHeader: '',
    responseBody: '',
    responseHeader: '',
    duration: 20,
    statusCode: 200,
    ts: '2021-12-12 12:12:21',
  },
];
